#!/usr/bin/env bash
set -x
source ./venv/bin/activate
git commit -am "automatic commit before build" || true
bumpversion patch src/setup.py
git push --tags
source ./build
git commit -am "updated static stuff"
cd src
git push || true
python setup.py bdist_egg bdist_wheel upload




