#!/usr/bin/env bash
set -x
set -e
source ./venv/bin/activate
git commit -am "automatic commit before build"
bumpversion patch src/setup.py
git push --tags
source ./build
git commit -am "updated static stuff"
cd src
python setup.py bdist_egg bdist_wheel upload
git push


