#!/usr/bin/env bash
set -x
source ./venv/bin/activate
git diff --quiet --exit-code --cached || git commit -m "automatic commit before build"
bumpversion patch src/setup.py
git push --tags
source ./build
git commit -am "updated static stuff"
cd src
python setup.py bdist_egg bdist_wheel upload




